//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.12.0+7dcc730
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>HomePage</summary>
	[PublishedModel("homePage")]
	public partial class HomePage : PublishedContentModel, IEspaBanners, INavigation, IPopup, ISchema, IScripts, ISeo, ISiteSettings, ISlider
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		public new const string ModelTypeAlias = "homePage";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<HomePage, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HomePage(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Awards: Enter the awards.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("awards")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Awards => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "awards");

		///<summary>
		/// Body Sections: Select the body sections.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bodySections")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel BodySections => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "bodySections");

		///<summary>
		/// Instagram Images: Select the Instagram images.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("instagramImages")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops> InstagramImages => this.Value<global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops>>(_publishedValueFallback, "instagramImages");

		///<summary>
		/// Instagram Link: Enter the Instagram link.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("instagramLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link InstagramLink => this.Value<global::Umbraco.Cms.Core.Models.Link>(_publishedValueFallback, "instagramLink");

		///<summary>
		/// Reviews: Enter the reviews.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("reviews")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel Reviews => this.Value<global::Umbraco.Cms.Core.Models.Blocks.BlockListModel>(_publishedValueFallback, "reviews");

		///<summary>
		/// Enable Espa Widget: Click here to enable espa widget.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[ImplementPropertyType("enableEspaWidget")]
		public virtual bool EnableEspaWidget => global::Umbraco.Cms.Web.Common.PublishedModels.EspaBanners.GetEnableEspaWidget(this, _publishedValueFallback);

		///<summary>
		/// Espa Widgets: Enter here the code if you have espa banner in your website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("espaWidgets")]
		public virtual string EspaWidgets => global::Umbraco.Cms.Web.Common.PublishedModels.EspaBanners.GetEspaWidgets(this, _publishedValueFallback);

		///<summary>
		/// Hide in Main Menu: Click this if you want to hide the page from navigation.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[ImplementPropertyType("hideInMainMenu")]
		public virtual bool HideInMainMenu => global::Umbraco.Cms.Web.Common.PublishedModels.Navigation.GetHideInMainMenu(this, _publishedValueFallback);

		///<summary>
		/// Hide in Navigation: Click this if you want to hide the page from navigation.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[ImplementPropertyType("hideInNavigation")]
		public virtual bool HideInNavigation => global::Umbraco.Cms.Web.Common.PublishedModels.Navigation.GetHideInNavigation(this, _publishedValueFallback);

		///<summary>
		/// Menu Image: Select the image menu.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MenuImage => global::Umbraco.Cms.Web.Common.PublishedModels.Navigation.GetMenuImage(this, _publishedValueFallback);

		///<summary>
		/// Menu Title: Enter the menu title for this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("menuTitle")]
		public virtual string MenuTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Navigation.GetMenuTitle(this, _publishedValueFallback);

		///<summary>
		/// Show in Footer Menu: Click this if you want to hide the page to appears in footer menu.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[ImplementPropertyType("showInFooterMenu")]
		public virtual bool ShowInFooterMenu => global::Umbraco.Cms.Web.Common.PublishedModels.Navigation.GetShowInFooterMenu(this, _publishedValueFallback);

		///<summary>
		/// Enable Popup: Click this property if you want to enable the popup.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[ImplementPropertyType("enablePopup")]
		public virtual bool EnablePopup => global::Umbraco.Cms.Web.Common.PublishedModels.Popup.GetEnablePopup(this, _publishedValueFallback);

		///<summary>
		/// Popup Booking Link: Enter the booking link for the pop up, if you want "Book now" button to appear.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popupBookingLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link PopupBookingLink => global::Umbraco.Cms.Web.Common.PublishedModels.Popup.GetPopupBookingLink(this, _publishedValueFallback);

		///<summary>
		/// Popup Image: Select the image for the pop up.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popupImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops PopupImage => global::Umbraco.Cms.Web.Common.PublishedModels.Popup.GetPopupImage(this, _publishedValueFallback);

		///<summary>
		/// Popup More Page Link: Select this link if you want the link to be "Learn More" button to appear.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popupMorePageLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link PopupMorePageLink => global::Umbraco.Cms.Web.Common.PublishedModels.Popup.GetPopupMorePageLink(this, _publishedValueFallback);

		///<summary>
		/// Popup Text: Enter the text for the popup.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popupText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString PopupText => global::Umbraco.Cms.Web.Common.PublishedModels.Popup.GetPopupText(this, _publishedValueFallback);

		///<summary>
		/// Popup Title: Enter the title for the popup.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("popupTitle")]
		public virtual string PopupTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Popup.GetPopupTitle(this, _publishedValueFallback);

		///<summary>
		/// Schema Json: Enter the Schema Json here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("schemaJson")]
		public virtual string SchemaJson => global::Umbraco.Cms.Web.Common.PublishedModels.Schema.GetSchemaJson(this, _publishedValueFallback);

		///<summary>
		/// Scripts In End Of Body: Enter here the scripts that you want to include in the end of the body element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("scriptsInEndOfBody")]
		public virtual string ScriptsInEndOfBody => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetScriptsInEndOfBody(this, _publishedValueFallback);

		///<summary>
		/// Scripts In Header: Enter here the scripts that you want to include in head element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("scriptsInHeader")]
		public virtual string ScriptsInHeader => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetScriptsInHeader(this, _publishedValueFallback);

		///<summary>
		/// Scripts In Start Of Body: Enter here the scripts that you want to include in the start of the body element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("scriptsInStartOfBody")]
		public virtual string ScriptsInStartOfBody => global::Umbraco.Cms.Web.Common.PublishedModels.Scripts.GetScriptsInStartOfBody(this, _publishedValueFallback);

		///<summary>
		/// Meta Description: Enter the Meta Description for this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Meta Title: Enter the Meta Title for this page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaTitle")]
		public virtual string MetaTitle => global::Umbraco.Cms.Web.Common.PublishedModels.Seo.GetMetaTitle(this, _publishedValueFallback);

		///<summary>
		/// Booking Link: Enter the booking link for the booking engine.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bookingLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link BookingLink => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetBookingLink(this, _publishedValueFallback);

		///<summary>
		/// Booking Online Link: Enter the booking online link.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("bookingOnlineLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link BookingOnlineLink => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetBookingOnlineLink(this, _publishedValueFallback);

		///<summary>
		/// Contact Details: Enter here the contact details.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("contactDetails")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString ContactDetails => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetContactDetails(this, _publishedValueFallback);

		///<summary>
		/// Map Image: Enter the map image here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mapImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops MapImage => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetMapImage(this, _publishedValueFallback);

		///<summary>
		/// Map Link: Enter the map link here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("mapLink")]
		public virtual global::Umbraco.Cms.Core.Models.Link MapLink => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetMapLink(this, _publishedValueFallback);

		///<summary>
		/// Social Media: Enter here the social media.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("socialMedia")]
		public virtual global::Umbraco.Cms.Core.Models.Blocks.BlockListModel SocialMedia => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetSocialMedia(this, _publishedValueFallback);

		///<summary>
		/// Website favicon: Select the favicon of the website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("websiteFavicon")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops WebsiteFavicon => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetWebsiteFavicon(this, _publishedValueFallback);

		///<summary>
		/// Website Logo: Select the logo of the website.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("websiteLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops WebsiteLogo => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetWebsiteLogo(this, _publishedValueFallback);

		///<summary>
		/// Website name: Enter the website name here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("websiteName")]
		public virtual string WebsiteName => global::Umbraco.Cms.Web.Common.PublishedModels.SiteSettings.GetWebsiteName(this, _publishedValueFallback);

		///<summary>
		/// Fallback Video Url: Enter here the fallback video url.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("fallbackVideoUrl")]
		public virtual string FallbackVideoUrl => global::Umbraco.Cms.Web.Common.PublishedModels.Slider.GetFallbackVideoUrl(this, _publishedValueFallback);

		///<summary>
		/// Hide Slider: Click this if you want to hide the slider.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[ImplementPropertyType("hideSlider")]
		public virtual bool HideSlider => global::Umbraco.Cms.Web.Common.PublishedModels.Slider.GetHideSlider(this, _publishedValueFallback);

		///<summary>
		/// Images Slider: Select the images you want to appear in the slider.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("imagesSlider")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.MediaWithCrops> ImagesSlider => global::Umbraco.Cms.Web.Common.PublishedModels.Slider.GetImagesSlider(this, _publishedValueFallback);

		///<summary>
		/// Text on Slider: Enter the text that will be on the slider.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("textOnSlider")]
		public virtual string TextOnSlider => global::Umbraco.Cms.Web.Common.PublishedModels.Slider.GetTextOnSlider(this, _publishedValueFallback);

		///<summary>
		/// Video Url: Enter here the video url.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("videoUrl")]
		public virtual string VideoUrl => global::Umbraco.Cms.Web.Common.PublishedModels.Slider.GetVideoUrl(this, _publishedValueFallback);

		///<summary>
		/// YouTube Video Url: Enter here the youtube video url.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("youTubeVideoUrl")]
		public virtual string YouTubeVideoUrl => global::Umbraco.Cms.Web.Common.PublishedModels.Slider.GetYouTubeVideoUrl(this, _publishedValueFallback);
	}
}
