//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.12.0+7dcc730
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "scripts"
	/// <summary>Scripts</summary>
	public partial interface IScripts : IPublishedElement
	{
		/// <summary>Scripts In End Of Body</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ScriptsInEndOfBody { get; }

		/// <summary>Scripts In Header</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ScriptsInHeader { get; }

		/// <summary>Scripts In Start Of Body</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ScriptsInStartOfBody { get; }
	}

	/// <summary>Scripts</summary>
	[PublishedModel("scripts")]
	public partial class Scripts : PublishedElementModel, IScripts
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		public new const string ModelTypeAlias = "scripts";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Scripts, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Scripts(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Scripts In End Of Body: Enter here the scripts that you want to include in the end of the body element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("scriptsInEndOfBody")]
		public virtual string ScriptsInEndOfBody => GetScriptsInEndOfBody(this, _publishedValueFallback);

		/// <summary>Static getter for Scripts In End Of Body</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetScriptsInEndOfBody(IScripts that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "scriptsInEndOfBody");

		///<summary>
		/// Scripts In Header: Enter here the scripts that you want to include in head element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("scriptsInHeader")]
		public virtual string ScriptsInHeader => GetScriptsInHeader(this, _publishedValueFallback);

		/// <summary>Static getter for Scripts In Header</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetScriptsInHeader(IScripts that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "scriptsInHeader");

		///<summary>
		/// Scripts In Start Of Body: Enter here the scripts that you want to include in the start of the body element.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("scriptsInStartOfBody")]
		public virtual string ScriptsInStartOfBody => GetScriptsInStartOfBody(this, _publishedValueFallback);

		/// <summary>Static getter for Scripts In Start Of Body</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.12.0+7dcc730")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetScriptsInStartOfBody(IScripts that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "scriptsInStartOfBody");
	}
}
